dnaSequence = "GCATGAGTTATTTTAGCTGGTACGGCCTTAGAGTGGGGGGTTAATCAGATTTAGTTAAAGACCGACCTAGTCGTATAATGTCAGGCACCGCATGAAGATGGTAACCCCTGTCGTCACGAGTGCCTACACCAGCCTAGAAAAAGCAACAGTCTGATGCCGATGGGGGTCGGCACAAACTTCGGGCTGCACCGATGTAACCTAGCTTTTGGAATCCAGTTCCGCGTTGGGCCCCTTATCGCTGTAGATCTCGAATATCTGTGCTCCCCATAACCGTGGAAATTGCCCTGTCGATTGATCCACTACAAACGAGCGTAAGTTTACGAGCCCAGATCATACATCGACAGGCATAACAATGCTGGCGGTGGCTGTCGACCATTCGCCTGAGATTGCAAGCTTTTTAGACTAAAACTGCACACCATGCTGGGTCCCCCTAGTGCGACTGAGCCTTTCATACCAAATGGCTTGCGGCAGCTTACGAGCCTTCTTGGATTCTCGAAGCTACGAATCATATAGAAACCCGTCGATTGTTGGGTACATCTCGCGGATCCCCGTAGTGGGGCTTGTTGGCCCCAAGTCTGTACGGAGTACTCACCTGACGAACTAGGCTATCCGCTGGACCTGTCATCTTCTAGTCGTCGTAAGCATATAACCATCGGATTTAGCGGACGGGACACTTAATCCTCCCAAGGGCGACGCTCCAGACGGCACATGGACACATTTGGTATACGCGGGTCTTCATCGGACGAAACACCGCAGCGGTTGGCACTGACGAAGCCTCTGAGTGAGCTTAATAAGAGCTAGATGAAGGCGGATTTTAGTGCGTATTCTCTCCAGCAGCGGCGTCCGACGCTAGAAAAAATTACCCACTTCCTGTCATCTACTGTACGCTACCCCTAGATTGCTAGTAACGACCGACGACCAACACCGCCTGATCGGGTTGTGCCGACCTATCTTAACCGGAGCTATATTGGTCCCGTTGAATCTTGCTGAT"

aCount = 0
cCount = 0
tCount = 0
gCount = 0

for c in dnaSequence:
    if c == 'A':
        aCount = aCount + 1
    elif c == 'C':
        cCount = cCount + 1
    elif c == 'T':
        tCount = tCount + 1
    elif c == 'G':
        gCount = gCount + 1

print (aCount)
print (cCount)
print (gCount)
print (tCount)

sequenceLength = len(dnaSequence)

print "Percentage of A's in sequence:", (float(aCount) / sequenceLength) * 100
print "Percentage of C's in sequence:", (float(cCount) / sequenceLength) * 100
print "Percentage of T's in sequence:", (float(tCount) / sequenceLength) * 100
print "Percentage of G's in sequence:", (float(gCount) / sequenceLength) * 100
